/* ==========================================================================
 * thermal_app.c  —  Thermal Logger with PID temperature control
 * Target : STM32F411CEU6 "Black Pill" @ 100 MHz  (STM32CubeIDE + HAL)
 *
 * ─── Wiring topology ────────────────────────────────────────────────────
 *
 *   5.0 V (USB) ──┬── R_top = 330 Ω ──┬── NTC 10D‑9 (~10 Ω) ── GND
 *                  │                    │
 *                  │                   PA0 (ADC1_IN0)
 *                  │                   (NODE voltage)
 *
 *   As temperature ↑, R_ntc ↓, so V_node ↑ (approaches 3.3 V).
 *   The ADC reference is 3.3 V; the divider supply is 5.0 V.
 *
 * ─── Heater wiring ─────────────────────────────────────────────────────
 *   PA6 (TIM3_CH1 PWM) → IRLZ44N gate → 10 Ω / 5 W resistor → USB 5 V
 *
 * ─── Module overview ────────────────────────────────────────────────────
 *   ThermalApp_Init()     ← call once after all MX_xxx_Init() in main.c
 *   ThermalApp_Loop()     ← call every iteration of while(1) in main.c
 *
 *   Each loop iteration (~1000 ms):
 *     1. ADC averaging        – 128 conversions polled, averaged
 *     2. Physics              – V_node, R_ntc, T_estimate (Beta model)
 *     3. PID control update   – computes new heater duty (0…1)
 *     4. EMA filters          – smooth display trace + auto‑scale stats
 *     5. Plot ring buffer     – push latest smoothed value
 *     6. PWM update           – write g_duty_cmd → TIM3 CCR1
 *     7. RAM log              – store {time, temp, duty} ring‑buffer entry
 *     8. OLED refresh         – every THERM_OLED_DIVIDER sample(s)
 *     9. Pace                 – HAL_Delay() for the remainder of 1000 ms
 *
 * ─── Debug tip ──────────────────────────────────────────────────────────
 *   Add to Live Expressions:
 *     dbg_adc_avg   – raw 12‑bit ADC average (0–4095)
 *     dbg_vnode     – node voltage measured by ADC (V, 0…3.3)
 *     dbg_rntc      – NTC resistance (Ω)
 *     dbg_temp_c    – raw (unfiltered) temperature estimate (°C)
 *     g_setpoint_c  – desired temperature (°C) – write here to change target
 *     g_duty_cmd    – PID output duty (0.0–1.0)
 *     pid.integral  – PID integrator state
 *     pid.deriv     – PID derivative state
 *     thermal_log_idx – number of log entries written so far
 * ========================================================================== */

#include "thermal_app.h"
#include "ssd1306.h"
#include "ring_buf.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

/* ── HAL handles (generated by CubeMX in main.c) ────────────────────────── */
extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;
#define PID_KP     2.0f
#define PID_KI     0.05f
#define PID_KD     5.0f
#define PID_TS     1.0f
#define PID_TAU_F  10.0f
/* ============================================================================
 * PUBLIC GLOBALS
 * ========================================================================== */

/*  g_duty_cmd is now driven by the PID controller.  You can still overwrite
 *  it from the debugger to force a particular duty, but normally it will be
 *  updated every loop by PID_Update().                                      */
volatile float g_duty_cmd = 0.0f;

/*  g_setpoint_c is the target temperature.  Write a new value in Live
 *  Expressions (e.g. 35.0) and the PID will smoothly bring the heater
 *  to that temperature.                                                     */
volatile float g_setpoint_c = 30.0f;
volatile float g_fan_duty = 0.0f;   /* Write from debugger for open-loop fan test */
/*  PID handle – contains all controller state.  Watch pid.integral and
 *  pid.deriv in the debugger to see what the controller is doing.           */
PID_Handle pid;

/*  RAM log ring‑buffer — all entries, circular.
 *  __attribute__((aligned(4))) ensures the debugger memory export is
 *  naturally aligned and easier to parse with a Python script.               */
__attribute__((aligned(4)))
ThermalLogEntry thermal_log[THERM_LOG_LEN];

volatile uint32_t thermal_log_idx = 0; /* Total entries written (ever)       */

/* ============================================================================
 * PRIVATE STATE
 * ========================================================================== */

/* ── Scrolling plot ring‑buffer (128 newest smoothed temperatures) ─────── */
static float   plot_buf[THERM_PLOT_LEN];
static uint8_t plot_head = 0;          /* Next write position; wraps at 128  */

/* ── EMA state ──────────────────────────────────────────────────────────── */
static float   ema_temp_display = 0.0f; /* Smoothed temperature for display  */
static float   ema_mean         = 0.0f; /* Slow‑tracking mean (plot center)  */
static float   ema_dev          = 1.0f; /* Mean‑abs‑deviation (plot scale)   */
static uint8_t ema_initialized  = 0;   /* 0 until first real reading         */
static float pid_temp = 0.0f;     /* EMA-filtered temp for PID input */
/* ── OLED refresh divider ───────────────────────────────────────────────── */
static uint8_t oled_div = 0;

/* ── Debug read‑back globals (watch in Live Expressions) ────────────────── */
volatile uint32_t dbg_adc_avg = 0;
volatile float    dbg_vnode   = 0.0f;
volatile float    dbg_rntc    = 0.0f;
volatile float    dbg_temp_c  = 0.0f;

/* ============================================================================
 * PRIVATE HELPERS
 * ========================================================================== */

/* ── adc_average ─────────────────────────────────────────────────────────
 *
 *   Collects `n` single ADC conversions via HAL polling and returns the
 *   integer mean.  At 1 Hz with n=128, each sample takes < 20 ms total —
 *   well within the 1000 ms budget.
 *
 *   CubeMX ADC1 prerequisites (MUST match):
 *     - Channel IN0 / PA0
 *     - 12‑bit right‑aligned, single conversion, software trigger
 *     - Scan mode OFF, DMA disabled
 *     - Sampling time: 84 or 144 cycles is fine for a 330 Ω source         */
static uint32_t adc_average(uint8_t n)
{
    uint32_t sum = 0;
    for (uint8_t i = 0; i < n; i++) {
        HAL_ADC_Start(&hadc1);
        if (HAL_ADC_PollForConversion(&hadc1, 10 /*ms timeout*/) == HAL_OK) {
            sum += HAL_ADC_GetValue(&hadc1);
        }
        HAL_ADC_Stop(&hadc1);
    }
    return sum / n;
}

/* ── adc_to_rntc ─────────────────────────────────────────────────────────
 *
 *   Derives R_NTC from the 12‑bit ADC reading.
 *
 *   Divider topology (R_top on TOP from 5.0 V, NTC on BOTTOM to GND):
 *
 *       5.0 V (VSUP)
 *           │
 *         R_top = 330 Ω
 *           │
 *         NODE  ──► PA0 (ADC, reference = THERM_ADC_VREF = 3.3 V)
 *           │
 *         R_NTC ≈ 10 Ω (10D‑9)
 *           │
 *          GND
 *
 *   The ADC measures V_node relative to 3.3 V.  The divider formula is:
 *       R_NTC = R_top × V_node / (VSUP − V_node)
 *   with V_node = 3.3 V × (adc / 4095).  Clamps prevent numerical issues. */
static float adc_to_rntc(uint32_t adc_val)
{
    /* Step 1: ADC counts → node voltage (relative to ADC VREF = 3.3 V) */
    float v = THERM_ADC_VREF * ((float)adc_val / 4095.0f);

    /* Step 2: Clamp low end — avoids divide‑by‑zero in the formula below */
    if (v < 0.001f) v = 0.001f;

    /* Step 3: Clamp high end.
     *   v must be strictly less than VSUP for the denominator (VSUP − v)
     *   to stay positive.  Under normal operation v ≤ THERM_ADC_VREF
     *   (ADC cannot read above its own reference), so the tighter clamp
     *   is simply (THERM_ADC_VREF − ε).                                  */
    float v_max = THERM_DIV_VSUP - 0.001f;
    if (v_max > (THERM_ADC_VREF - 0.001f))
        v_max = THERM_ADC_VREF - 0.001f;
    if (v > v_max) v = v_max;

    /* Step 4: Correct divider formula for VSUP → Rtop → node → Rntc → GND
     *   R_NTC = R_top × V_node / (VSUP − V_node)                        */
    float rntc = THERM_RTOP * (v / (THERM_DIV_VSUP - v));

    /* Step 5: Clamp to physically plausible range for a 10D‑9 */
    if (rntc <    0.1f) rntc =    0.1f;
    if (rntc > 5000.0f) rntc = 5000.0f;

    return rntc;
}

/* ── rntc_to_celsius ─────────────────────────────────────────────────────
 *
 *   Steinhart‑Hart simplified (two‑parameter Beta model):
 *
 *       1/T = 1/T0 + (1/Beta) × ln(R / R0)
 *
 *   ⚠  APPROXIMATE — 10D‑9 is an inrush limiter, not a precision sensor.
 *      Result is monotonic (hotter → lower R → higher T) but absolute
 *      accuracy depends on how well Beta = 3500 K matches your part.
 *      Recalibrate: measure R at 25 °C (R0) and at a second known temp,
 *      then compute  Beta = ln(R1/R2) / (1/T1 − 1/T2).                  */
static float rntc_to_celsius(float rntc)
{
    float inv_T = (1.0f / THERM_T0_K)
                + (1.0f / THERM_BETA) * logf(rntc / THERM_R0);

    /* Guard: prevent division by zero or negative absolute temperature */
    if (inv_T < 1e-6f) inv_T = 1e-6f;

    return (1.0f / inv_T) - 273.15f;   /* Kelvin → Celsius              */
}

/* ── ema_step ────────────────────────────────────────────────────────────
 *   One exponential moving average update.
 *   new_state = old_state + alpha × (new_value − old_state)            */
static inline float ema_step(float state, float value, float alpha)
{
    return state + alpha * (value - state);
}

/* ── pwm_update ──────────────────────────────────────────────────────────
 *
 *   Reads g_duty_cmd (0.0 … 1.0), clamps it, and writes the matching
 *   CCR value to TIM3 CH1.
 *
 *   ARR is read live from the hardware register so this function stays
 *   correct even if you change the CubeMX period setting.
 *
 *   CCR = ARR × duty   (ARR+1 ticks per period, CCR ticks HIGH)        */
static void pwm_update(void)
{
    float cmd = g_duty_cmd;
    if (cmd < -1.0f) cmd = -1.0f;
    if (cmd >  1.0f) cmd =  1.0f;

    uint32_t arr = __HAL_TIM_GET_AUTORELOAD(&htim3);

    float heater_duty;
    float fan_duty;

    if (cmd >= 0.0f) {
        heater_duty = cmd;
        fan_duty    = 0.0f;
    } else {
        heater_duty = 0.0f;
        fan_duty    = -cmd;
    }

    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1,
                          (uint32_t)(heater_duty * (float)arr));
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2,
                          (uint32_t)(fan_duty * (float)arr));

    g_fan_duty = fan_duty;
}
/* ── log_sample ──────────────────────────────────────────────────────────
 *
 *   Appends one {time, temp, duty} entry to the ring buffer.
 *   Wraps around silently so the log always holds the most recent
 *   THERM_LOG_LEN samples.
 *
 *   To export in STM32CubeIDE debugger:
 *     1. Pause execution.
 *     2. Window → Show View → Memory Browser → type: thermal_log
 *     3. Export Raw Binary, size = THERM_LOG_LEN × 12 = 24576 bytes.
 *     4. Parse in Python:
 *          import numpy as np
 *          d = np.fromfile('thermal.bin', dtype=np.float32).reshape(-1, 3)
 *          # columns: [0] time_s   [1] temp_c   [2] duty               */
static void log_sample(float temp_c, float heater_duty, float fan_duty)
{
    uint32_t idx = thermal_log_idx % THERM_LOG_LEN;

    thermal_log[idx].time_s      = HAL_GetTick() * 0.001f;
    thermal_log[idx].temp_c      = temp_c;
    thermal_log[idx].setpoint_c  = g_setpoint_c;   /* ← add this */
    thermal_log[idx].heater_duty = heater_duty;
    thermal_log[idx].fan_duty    = fan_duty;

    thermal_log_idx++;
}

/* ── format_fixed1 ───────────────────────────────────────────────────────
 *
 *   Formats a float as "±XXX.X" (one decimal place) into buf without
 *   using %f / float printf, so it works even if the linker flag
 *   -u _printf_float is not set.
 *
 *   Returns the number of characters written (not including '\0').
 *
 *   The SSD1306 driver only renders ASCII 32‑90; this function outputs
 *   only digits, '-', and '.', which all fall in that range.           */
static int format_fixed1(char *buf, int buf_len, float val)
{
    int sign = (val < 0.0f) ? 1 : 0;
    if (sign) val = -val;

    int32_t tenths = (int32_t)(val * 10.0f + 0.5f); /* e.g. 25.3 → 253 */
    int32_t whole  = tenths / 10;
    int32_t frac   = tenths % 10;

    if (sign)
        return snprintf(buf, buf_len, "-%ld.%ld", (long)whole, (long)frac);
    else
        return snprintf(buf, buf_len, "%ld.%ld",  (long)whole, (long)frac);
}

/* ── oled_update ─────────────────────────────────────────────────────────
 *
 *   Redraws the full 128×64 OLED dashboard:
 *
 *   ┌──────────────────────────────────┐
 *   │ A:2048  V:1.65                   │  row  0 – ADC avg, node voltage
 *   │ R: 10.0  T: 25.0C               │  row  8 – Rntc, temperature
 *   │ DUTY:  0 PCT                     │  row 16 – heater duty %
 *   ├──────────────────────────────────┤  row 20 – separator line
 *   │                                  │
 *   │   [scrolling temperature plot]   │  rows 22–63  (42 px tall)
 *   │                                  │
 *   └──────────────────────────────────┘
 *
 *   Plot details:
 *     • X axis  : time, oldest left → newest right (128 samples)
 *     • Y axis  : auto‑centered on ema_mean, ±(K × ema_dev) half‑span
 *     • Values  : connected line segments (one Bresenham per pixel step)
 *
 *   NOTE: ssd1306_print() only renders ASCII 32–90.
 *   All strings here use uppercase + digits + common punctuation only.   */
static void oled_update(uint32_t adc_avg, float vnode, float rntc,
                        float temp_c, int duty_pct)
{
    char buf[22];

    ssd1306_clear();

    /* ── Row 0: ADC raw average + node voltage ──────────────────────── */
    {
        char v_str[8];
        format_fixed1(v_str, sizeof(v_str), vnode);
        snprintf(buf, sizeof(buf), "A:%4lu V:%s",
                 (unsigned long)adc_avg, v_str);
    }
    ssd1306_print(0, 0, buf);

    /* ── Row 8: NTC resistance + temperature ───────────────────────── */
    {
        char r_str[8], t_str[8];
        format_fixed1(r_str, sizeof(r_str), rntc);
        format_fixed1(t_str, sizeof(t_str), temp_c);
        snprintf(buf, sizeof(buf), "R:%s T:%sC", r_str, t_str);
    }
    ssd1306_print(0, 8, buf);

    /* ── Row 16: Heater duty ────────────────────────────────────────── */
    snprintf(buf, sizeof(buf), "DUTY:%3d PCT", duty_pct);
    ssd1306_print(0, 16, buf);

    /* ── Separator line ─────────────────────────────────────────────── */
    ssd1306_draw_line(0, 20, 127, 20);

    /* ── Scrolling temperature plot ─────────────────────────────────── *
     *
     *  Auto‑centering / auto‑scaling:
     *
     *   plot_center  = ema_mean  (follows the signal mean slowly)
     *   half_span    = max( K × ema_dev,  MIN_SPAN/2 )
     *
     *  So if ema_dev = 0.5 °C and K = 3:
     *     half_span = 1.5 °C  → plot covers ±1.5 °C = 3 °C full range
     *     A 1 °C change occupies 42 × (1/3) ≈ 14 pixels — very visible.
     *
     *  Mapping (0 = top of OLED):
     *     screen_y = PLOT_BOTTOM − round( (val − plot_min)/span × PLOT_H )
     *
     *  The ring buffer stores the EMA‑filtered temperature so the trace
     *  is already smooth — no further filtering needed here.            */

    const uint8_t PLOT_TOP    = 22;
    const uint8_t PLOT_BOTTOM = 63;
    const uint8_t PLOT_H      = PLOT_BOTTOM - PLOT_TOP;   /* 41 px       */

    float half_span = THERM_PLOT_K * ema_dev;
    if (half_span < THERM_PLOT_MIN_SPAN / 2.0f)
        half_span = THERM_PLOT_MIN_SPAN / 2.0f;

    float plot_min = ema_mean - half_span;
    float span     = 2.0f * half_span;                    /* Always > 0  */

    int32_t prev_y = -1;

    for (uint8_t x = 0; x < THERM_PLOT_LEN; x++) {

        /* Read oldest → newest from the ring buffer.
         * plot_head points to the NEXT write slot, so plot_head is the
         * oldest entry (it was overwritten PLOT_LEN iterations ago).    */
        uint8_t idx = (uint8_t)((plot_head + x) % THERM_PLOT_LEN);
        float val = plot_buf[idx];

        /* Normalise 0..1, clamp */
        float norm = (val - plot_min) / span;
        if (norm < 0.0f) norm = 0.0f;
        if (norm > 1.0f) norm = 1.0f;

        /* Y=0 is top, so higher temperature → lower screen_y */
        int32_t y = (int32_t)PLOT_BOTTOM - (int32_t)(norm * (float)PLOT_H);

        if (prev_y >= 0) {
            ssd1306_draw_line(x - 1, (uint8_t)prev_y, x, (uint8_t)y);
        } else {
            ssd1306_draw_pixel(x, (uint8_t)y, 1);
        }
        prev_y = y;
    }

    ssd1306_update();
}

/* ============================================================================
 * PUBLIC API
 * ========================================================================== */

/* ── ThermalApp_Init ─────────────────────────────────────────────────────
 *
 *   Call once from main.c after ALL MX_xxx_Init() peripheral inits.
 *
 *   What it does:
 *     • Starts TIM3 PWM output on CH1 (PA6)  — heater starts at 0 %
 *     • Zeroes the plot ring‑buffer and the log buffer
 *     • Shows a brief splash screen on the OLED
 *     • Initialises the PID controller with the tuned gains
 * ------------------------------------------------------------------------ */
/* ==========================================================================
 * PUBLIC API
 * ========================================================================== */
void ThermalApp_Init(void)
{
    /* 1. Clear event queue — must be empty before heartbeat starts */
    RingBuffer_Init();

    /* 2. Start PWM on both channels at 0% duty (safe state)
     *    CubeMX configured the timer but did NOT start it.
     *    We start it here with CCR=0 so the MOSFET gate stays LOW
     *    until the PID deliberately commands a nonzero duty.        */
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);       /* heater PA6 */
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, 0);
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);       /* fan PA7    */
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, 0);

    /* 3. Zero display/log state — prevents garbage on first OLED frame */
    memset(plot_buf, 0, sizeof(plot_buf));
    plot_head = 0;
    memset(thermal_log, 0, sizeof(thermal_log));
    thermal_log_idx = 0;

    /* 4. Read initial temperature
     *    Three-stage pipeline: ADC counts → resistance → temperature.
     *    Each function returns a different type, so use matching variables.
     *    This reading seeds PID_Init so the derivative term
     *    doesn't see a false step on the first tick.                   */
    uint32_t adc_raw   = adc_average(THERM_ADC_OVERSAMPLE);
    float    init_rntc = adc_to_rntc(adc_raw);
    float    init_temp = rntc_to_celsius(init_rntc);
    pid_temp = init_temp;
    /* 5. Initialise PID — gains from #defines in thermal_app.h */
    PID_Init(&pid, PID_KP, PID_KI, PID_KD,
             PID_TS, PID_TAU_F, init_temp);

    /* 6. Splash screen — visual proof that init completed */
    ssd1306_clear();
    ssd1306_print(0, 0, "THERMAL CTRL");
    ssd1306_print(0, 16, "V0.6 INIT OK");
    ssd1306_update();
    HAL_Delay(800);

    /* 7. Start 1 Hz heartbeat — MUST BE LAST
     *    From this moment, TIM2 ISR fires every 1s and pushes
     *    EVT_PID_TICK into the ring buffer.  Everything above
     *    must be ready before this line.                          */
    HAL_TIM_Base_Start_IT(&htim2);
}
void ThermalApp_Loop(void) // <--- FIXED: No arguments needed yet
{
    Event_t current_event; // <--- DECLARE THE EVENT VARIABLE

    // --- STEP 1: SENSING (Always Run) ---
    uint32_t adc_avg = adc_average(THERM_ADC_OVERSAMPLE);
    float vnode = THERM_ADC_VREF * ((float)adc_avg / 4095.0f);
    float rntc = adc_to_rntc(adc_avg);
    float temp_c = rntc_to_celsius(rntc);

    // Update debug globals
    dbg_adc_avg = adc_avg;
    dbg_vnode = vnode;
    dbg_rntc = rntc;
    dbg_temp_c = temp_c;

    // --- STEP 2: EVENT PROCESSING (The New Engine) ---
    // Drain the queue. If multiple ticks piled up, process them all.
    while (RingBuffer_Pop(&current_event)) // <--- FIXED: Pass address (&)
    {
        switch (current_event) // <--- FIXED: C syntax with parentheses
        {
        case EVT_PID_TICK:
            // Filter temp before PID sees it
            pid_temp = pid_temp + 0.02f * (temp_c - pid_temp);

                // PID now sees filtered temperature
                g_duty_cmd = PID_Update(&pid, g_setpoint_c, pid_temp);

                // 2. Update EMA Filters (Copied from old loop)
                if (!ema_initialized) {
                    ema_temp_display = temp_c;
                    ema_mean         = temp_c;
                    ema_dev          = 1.0f;
                    ema_initialized  = 1;
                } else {
                    ema_temp_display = ema_step(ema_temp_display, temp_c, THERM_EMA_DISPLAY);
                    ema_mean = ema_step(ema_mean, ema_temp_display, THERM_EMA_MEAN);

                    float abs_dev = ema_temp_display - ema_mean;
                    if (abs_dev < 0.0f) abs_dev = -abs_dev;
                    ema_dev = ema_step(ema_dev, abs_dev, THERM_EMA_DEV);
                    if (ema_dev < 0.05f) ema_dev = 0.05f;
                }

                // 3. Update Plot Buffer
                plot_buf[plot_head] = ema_temp_display;
                plot_head = (uint8_t)((plot_head + 1) % THERM_PLOT_LEN);

                // 4. Log Data
                log_sample(ema_temp_display, g_duty_cmd, g_fan_duty);
                break; // <--- CRITICAL: Don't fall through to other cases!

            case EVT_START_CMD:
                // Optional: Handle manual start later
                break;

            case EVT_STOP_CMD:
                // Optional: Handle stop later
                break;

            default:
                break;
        }
    }

    // --- STEP 3: ACTUATION (Always Run) ---
    // Update PWM to reflect latest g_duty_cmd
    pwm_update();

    // --- STEP 4: UI (Always Run, Throttled) ---
    static uint8_t oled_div = 0;
    oled_div++;
    if (oled_div >= THERM_OLED_DIVIDER) {
        oled_div = 0;
        int duty_pct = (int)(g_duty_cmd * 100.0f + 0.5f);
        if (duty_pct < 0) duty_pct = 0;
        if (duty_pct > 100) duty_pct = 100;

        oled_update(adc_avg, vnode, rntc, ema_temp_display, duty_pct);
    }

    // --- STEP 5: TIMING ---
    // The HAL_Delay is GONE. The loop runs as fast as possible.
    // The PID is paced by the Timer Interrupt, not by this loop.
}
